//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Id { get; set; }
        public Nullable<int> Item1 { get; set; }
        public Nullable<int> Item2 { get; set; }
        public Nullable<int> Item3 { get; set; }
        public Nullable<int> Item4 { get; set; }
        public Nullable<int> Item5 { get; set; }
        public Nullable<int> Item6 { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Food Food1 { get; set; }
        public virtual Food Food2 { get; set; }
        public virtual Food Food3 { get; set; }
        public virtual Food Food4 { get; set; }
        public virtual Food Food5 { get; set; }

        public int total()
        {
            int t = Convert.ToInt32(Food.Price);
            t += Convert.ToInt32(Food1.Price);
            t += Convert.ToInt32(Food2.Price);
            t += Convert.ToInt32(Food3.Price);
            t += Convert.ToInt32(Food4.Price);
            t += Convert.ToInt32(Food5.Price);
            return t;
        }
    }
}
